### ISSUE TITLE
Unprocessed leads from vendor id 05685

### ISSUE THREAD

**Issue by poatekmaxbeber** [CAR-ResearchXRM/CARRLEADLISTENERS#7]
At present, there are **26** unprocessed leads from vendor id 05685. There is no Ford dealership associated with this vendor id in the database.

Does it require any further action or should these records be ignored?

```SQL
    SELECT d.CRMInactive,
           dc.VendorId,
           d.DBName,
           d.CrmInactive
      FROM [CARDB].[dbo].[tblDealerships] d WITH (READUNCOMMITTED) 
      JOIN [CARDB].[LEAD_PROCESSING].[tblDealershipConfig] dc WITH (READUNCOMMITTED) ON d.DealershipID = dc.DealershipID
     WHERE dc.Manufacturer = 'Ford'
       AND dc.VendorID = '05685'
```

The list of leads received from this particular vendor can be retrieved as follow:
```SQL
 SELECT a.*
   FROM [CAR_LOGGING].[dbo].[CarListener_HTTP_Inbound] a WITH (READUNCOMMITTED) 
  WHERE a.Manufacturer = 'Ford'
    AND a.DealershipID IS NULL
    AND a.HttpInboundDocument LIKE '%<id sequence="1" source="FordDirect">05685</id>%'
    AND a.ComputerName LIKE '%HOU%'
  ORDER BY a.HttpInboundTableId  DESC
```

**Comment by mdonnelly314** [comment]
I saw that and have forwarded the issue to Lenice and Tomika
Please leave the error
Until they respond


Mike

**Comment by poatekmaxbeber** [comment]
Do you have any updates on this issue?

There are **394 ** unprocessed leads from vendor id 05685 until now.

**Comment by mdonnelly314** [comment]
Is this an invalid vendorID  ???

**Comment by poatekmaxbeber** [comment]
The dealership was created on April 12th and the upcoming leads will be processed with success.
